version: '3'

services:
  apidoc:
    container_name: apidoc-collector
    image: self/apidoc:1.0.0
    restart: always
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - "${HOST_PROJECT_DIR}:/opt/from-host/project"
      - "${HOST_DOC_DIR}:/opt/from-host/apidoc"
    command:
      - /bin/sh
      - -c
      - |
        chmod +x /opt/from-host/project/apidoc-generator/main
        chmod +x /opt/from-host/project/apidoc-generator/run.sh
        /opt/from-host/project/apidoc-generator/run.sh
        tail -f /dev/null